#!/bin/bash -e

npm shrinkwrap "$@"
echo '''
var fs = require("fs");
var shrinkwrap = require("./npm-shrinkwrap.json");

function gitDep(rep) {
    return /^git/.test(rep);
}

function replacer(key, val) {
    if (!this.version) {
        return val;
    }
    if (key === "from" && !gitDep(this.resolved)) {
        return undefined;
    }
    if (key === "resolved" && !gitDep(val) && this.from !== val) {
        return undefined;
    }
    return val;
}

fs.writeFileSync("./npm-shrinkwrap.json", JSON.stringify(shrinkwrap, replacer, 2));
''' | node
